import { motion, AnimatePresence } from "framer-motion";
import { Loader2, XCircle, Zap, Search, Database } from "lucide-react";
import { useState, useEffect } from "react";
import type { ScanProgress as ProgressType } from "../../types/scan";
import { ScanStats } from "./ScanStats";

interface ScanProgressProps {
    progress: ProgressType | null;
    path: string;
    onCancel: () => void;
}

const FUN_FACTS = [
    "Did you know? The average PC has 47GB of duplicate files.",
    "Emptying the recycle bin regularly can save gigabytes of space.",
    "Browser cache can easily grow to over 5GB if not cleared.",
    "Uninstalling unused large games is the fastest way to regain space.",
    "Temporary files are generated by apps but rarely cleaned up automatically.",
];

export function ScanProgress({ progress, path, onCancel }: ScanProgressProps) {
    const rootName = path.replace(/[/\\]$/, "").split(/[/\\]/).pop() || path;
    const [factIndex, setFactIndex] = useState(0);

    useEffect(() => {
        const interval = setInterval(() => {
            setFactIndex(i => (i + 1) % FUN_FACTS.length);
        }, 4000);
        return () => clearInterval(interval);
    }, []);

    const isPhase1 = progress ? (progress.current_path.includes("Phase 1") || (progress.bytes_scanned === 0 && progress.files_scanned > 0 && !progress.current_path.includes("Phase 4"))) : true;
    const isFinishing = !progress && path !== "Unknown Path";
    const phaseText = isFinishing ? "Finalizing results..." : (progress?.current_path || (isPhase1 ? "Indexing file system..." : "Calculating sizes..."));
    const currentFact = FUN_FACTS[factIndex];

    // Determine which icon to show based on the phase text
    const getPhaseIcon = () => {
        if (isFinishing) return <Zap className="w-9 h-9 text-yellow-500/60 animate-pulse" />;
        if (phaseText.includes("Phase 1")) return <Search className="w-9 h-9 text-blue-500/60" />;
        if (phaseText.includes("Phase 2")) return <Search className="w-9 h-9 text-blue-500/60" />;
        if (phaseText.includes("Phase 3")) return <Database className="w-9 h-9 text-green-500/60" />;
        if (phaseText.includes("Phase 4")) return <Loader2 className="w-9 h-9 text-purple-500/60 animate-spin" />;
        return isPhase1 ? <Search className="w-9 h-9 text-blue-500/60" /> : <Database className="w-9 h-9 text-green-500/60" />;
    };

    const getPhaseColor = () => {
        if (isFinishing) return "text-yellow-500";
        if (phaseText.includes("Phase 3")) return "text-green-500";
        if (phaseText.includes("Phase 4")) return "text-purple-500";
        return isPhase1 ? "text-blue-500" : "text-green-500";
    };

    const getPhaseBg = () => {
        if (isFinishing) return "bg-yellow-500/10";
        if (phaseText.includes("Phase 3")) return "bg-green-500/10";
        if (phaseText.includes("Phase 4")) return "bg-purple-500/10";
        return isPhase1 ? "bg-blue-500/10" : "bg-green-500/10";
    };

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            transition={{ duration: 0.3 }}
            className="flex-1 flex flex-col items-center justify-center p-8 w-full max-w-4xl mx-auto"
        >
            {/* Central icon animation block */}
            <div className="relative mb-8 flex flex-col items-center gap-4 min-h-48">
                <AnimatePresence mode="wait">
                    <motion.div
                        key={phaseText}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -10 }}
                        transition={{ duration: 0.4 }}
                        className="flex flex-col items-center"
                    >
                        <div className="relative mb-4">
                            <div className={`w-20 h-20 rounded-full ${getPhaseBg()} flex items-center justify-center`}>
                                {getPhaseIcon()}
                            </div>
                            <motion.div
                                className={`absolute inset-0 rounded-full border-2 ${getPhaseColor().replace('text-', 'border-')}/30`}
                                animate={{ scale: [1, 1.4, 1.4], opacity: [0.5, 0, 0] }}
                                transition={{ repeat: Infinity, duration: 2, ease: "easeOut" }}
                            />
                        </div>
                        <h2 className={`text-2xl font-bold tracking-tight ${getPhaseColor()} text-center`}>
                            {phaseText}
                        </h2>
                        <p className="text-sm font-medium text-muted-foreground mt-1 text-center">
                            Scanning <span className="text-foreground">{rootName}</span>
                        </p>
                    </motion.div>
                </AnimatePresence>
            </div>

            <div className="w-full max-w-3xl glass p-8 rounded-2xl relative overflow-hidden transition-colors duration-500" style={{ borderColor: isPhase1 ? 'rgba(59,130,246,0.1)' : 'rgba(34,197,94,0.1)' }}>
                {/* Animated shimmer progress bar */}
                <div className="absolute top-0 left-0 w-full h-0.5 bg-secondary overflow-hidden">
                    <motion.div
                        className="absolute h-full"
                        style={{ width: "40%", background: `linear-gradient(to right, transparent, ${isPhase1 ? '#3b82f6' : '#22c55e'}, transparent)` }}
                        animate={{ left: ["-40%", "140%"] }}
                        transition={{ repeat: Infinity, duration: 1.8, ease: "linear" }}
                    />
                </div>

                {progress ? (
                    <ScanStats progress={progress} />
                ) : (
                    <div className="h-32 flex flex-col items-center justify-center gap-3">
                        <Zap className="w-8 h-8 text-primary/40 animate-pulse" />
                        <p className="text-muted-foreground text-sm animate-pulse">
                            Initializing scan engine…
                        </p>
                    </div>
                )}

                {/* Fun facts */}
                <div className="mt-8 pt-6 border-t border-border/50 text-center">
                    <div className="h-6">
                        <AnimatePresence mode="wait">
                            <motion.p
                                key={factIndex}
                                initial={{ opacity: 0, y: 5 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -5 }}
                                className="text-sm font-medium text-muted-foreground italic"
                            >
                                {currentFact}
                            </motion.p>
                        </AnimatePresence>
                    </div>
                </div>
            </div>

            <motion.button
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                onClick={onCancel}
                className="mt-8 flex items-center gap-2 px-6 py-3 rounded-xl bg-destructive/10 text-destructive hover:bg-destructive hover:text-destructive-foreground transition-colors font-medium"
            >
                <XCircle size={18} />
                Cancel Scan
            </motion.button>
        </motion.div>
    );
}
